parameters:
#    comensee_shell.example.class: Comensee\ShellBundle\Example

services:
#    comensee_shell.example:
#        class: %comensee_shell.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

